
open_collective: # Replace with a single Open Collective username
ko_fi: "https://ko-fi.com/jptrzy"
liberapay: # Replace with a single Liberapay username
custom: "https://jptrzy.github.io/donations.html"
